server:
  port: 9292

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/soniaarnaudova/config-server
          default-label: main
          clone-on-start: true
    loadbalancer:
      ribbon:
        enabled: false